name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4  # v4.1.7

      - name: Setup Deno
        uses: denoland/setup-deno@v4  # v1.1.2
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies
        uses: actions/cache@v4  # v4.1.2
        with:
          path: ~/.cache/deno
          key: deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            deno-

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
